/* ELVORA v5 — production storefront bridge */
(() => {
  const C=window.ELVORA_CONFIG||{};
  const enabled=Boolean(C.SUPABASE_URL&&C.SUPABASE_ANON_KEY&&window.supabase);
  if(!enabled){document.querySelector('.admin-note')?.replaceChildren(document.createTextNode('Demo mode. Connect Supabase to enable shared products, accounts, orders, coupons and admin dashboard.'));return;}
  const db=window.supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
  const toast=m=>{const x=$('#toast');if(!x)return;x.textContent=m;x.classList.add('show');clearTimeout(window.__et);window.__et=setTimeout(()=>x.classList.remove('show'),2500)};
  const open=id=>{const x=$('#'+id);if(x){x.classList.add('open');x.setAttribute('aria-hidden','false');document.body.classList.add('modal-open')}};
  const close=id=>{const x=$('#'+id);if(x){x.classList.remove('open');x.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}};
  let session=null,profile=null;
  const getCart=()=>{try{return JSON.parse(localStorage.getItem('elvora-cart')||'[]')}catch{return[]}};
  const cartTotal=()=>getCart().reduce((a,i)=>a+Number(i.price)*Number(i.qty),0);
  async function syncProducts(){
    const {data,error}=await db.from('products').select('id,name,category,price,image,description,stock').eq('active',true).order('created_at');
    if(error||!data?.length)return;
    const grouped={Chair:[],Beds:[],Sofa:[],Lamp:[]};
    data.forEach(p=>{if(grouped[p.category])grouped[p.category].push([p.image,p.name,String(p.price),p.id,p.description||'',p.stock])});
    localStorage.setItem('elvora-products',JSON.stringify(grouped));
    window.dispatchEvent(new Event('elvora-products-updated'));
  }
  async function loadProfile(){const {data:{session:s}}=await db.auth.getSession();session=s;profile=null;if(s?.user){const {data}=await db.from('profiles').select('*').eq('id',s.user.id).maybeSingle();profile=data||{role:'customer',full_name:s.user.user_metadata?.full_name||''}};updateAccount();}
  function updateAccount(){const login=$('[data-account-view="login"]'),signup=$('[data-account-view="signup"]'),user=$('#accountUser');if(!login||!signup||!user)return;if(session?.user){login.classList.add('hidden');signup.classList.add('hidden');user.classList.remove('hidden');$('#accountUserName').textContent=profile?.full_name||'ELVORA Customer';$('#accountUserEmail').textContent=session.user.email||'';}else{login.classList.remove('hidden');signup.classList.add('hidden');user.classList.add('hidden')}}
  $$('.account-tab').forEach(t=>t.onclick=()=>{$$('.account-tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');const v=t.dataset.accountTab;$('[data-account-view="login"]').classList.toggle('hidden',v!=='login');$('[data-account-view="signup"]').classList.toggle('hidden',v!=='signup');});
  $$('[data-close-app]').forEach(x=>x.onclick=()=>close(x.dataset.closeApp));
  $('#loginForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await db.auth.signInWithPassword({email:String(f.get('email')).trim(),password:String(f.get('password'))});if(error)return toast(error.message);await loadProfile();close('accountModal');toast('Welcome back to ELVORA')};
  $('#signupForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {data,error}=await db.auth.signUp({email:String(f.get('email')).trim(),password:String(f.get('password')),options:{data:{full_name:String(f.get('name')).trim()}}});if(error)return toast(error.message);if(data.session){await loadProfile();close('accountModal');toast('Account created')}else toast('Account created — check your email')};
  $('#logoutBtn').onclick=async()=>{await db.auth.signOut();await loadProfile();toast('Signed out')};
  $('#demoLogin').onclick=()=>toast('Create a real ELVORA account to continue');
  $('#ordersBtn').onclick=async()=>{close('accountModal');await renderOrders();open('ordersModal')};
  db.auth.onAuthStateChange(()=>setTimeout(loadProfile,0));
  async function renderOrders(){const list=$('#ordersList');if(!session?.user){list.innerHTML='<p class="empty-state">Sign in to view your orders.</p>';return}const {data,error}=await db.from('orders').select('*,order_items(*)').eq('user_id',session.user.id).order('created_at',{ascending:false});if(error){list.innerHTML=`<p class="empty-state">${error.message}</p>`;return}list.innerHTML=data?.length?data.map(o=>`<article class="order-card"><div><strong>#${o.id.slice(0,8).toUpperCase()}</strong><span>${new Date(o.created_at).toLocaleString()}</span></div><p>${(o.order_items||[]).map(i=>`${i.product_name} × ${i.quantity}`).join(', ')}</p><b>₹ ${Number(o.total).toFixed(2)}</b><small>${o.payment_method==='online'?'Online':'COD'} · ${o.payment_status} · <strong>${o.order_status}</strong></small></article>`).join(''):'<p class="empty-state">No orders yet.</p>'}
  async function applyCoupon(code){code=String(code||'').trim().toUpperCase();if(!code)return{discount:0};const {data,error}=await db.from('coupons').select('*').eq('code',code).eq('active',true).maybeSingle();if(error||!data)return{error:'Invalid or inactive coupon'};const subtotal=cartTotal();if(subtotal<Number(data.min_order))return{error:`Minimum order is ₹${Number(data.min_order).toFixed(0)}`};if(data.expires_at&&new Date(data.expires_at)<new Date())return{error:'Coupon expired'};if(data.usage_limit&&data.used_count>=data.usage_limit)return{error:'Coupon limit reached'};let discount=data.type==='percent'?subtotal*Number(data.value)/100:Number(data.value);if(data.max_discount)discount=Math.min(discount,Number(data.max_discount));return{discount,code:data.code}}
  let coupon={discount:0,code:''};
  $('#couponBtn')?.addEventListener('click',async()=>{const code=$('#couponInput')?.value;const r=await applyCoupon(code);if(r.error){coupon={discount:0,code:''};return toast(r.error)}coupon=r;toast(`Coupon ${r.code} applied`);renderCheckoutSummary()});
  function renderCheckoutSummary(){const items=getCart();$('#checkoutItems').innerHTML=items.map(i=>`<div><span>${i.name} × ${i.qty}</span><span>₹ ${(Number(i.price)*i.qty).toFixed(2)}</span></div>`).join('')+`<div><span>Subtotal</span><span>₹ ${cartTotal().toFixed(2)}</span></div>`+(coupon.discount?`<div><span>Discount (${coupon.code})</span><span>− ₹ ${coupon.discount.toFixed(2)}</span></div>`:'');$('#checkoutTotal').textContent=`₹ ${Math.max(0,cartTotal()-coupon.discount).toFixed(2)}`}
  $('#checkoutBtn').onclick=async()=>{if(!getCart().length)return toast('Your bag is empty');if(!session?.user){close('checkoutModal');open('accountModal');return}coupon={discount:0,code:''};$('#couponInput')&&($('#couponInput').value='');renderCheckoutSummary();close('cartDrawer');open('checkoutModal')};
  async function payOnline(draft){const r=await fetch('/api/create-payment-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount:draft.total,receipt:`ELV-${Date.now()}`})});const p=await r.json();if(!r.ok)throw Error(p.error||'Payment service unavailable');if(!window.Razorpay){await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=res;s.onerror=()=>rej(Error('Payment gateway could not load'));document.head.appendChild(s)})}return new Promise((res,rej)=>{const rz=new Razorpay({key:p.keyId,amount:p.amount,currency:p.currency,name:'ELVORA',description:'Furniture order',order_id:p.id,prefill:{name:draft.name,email:draft.email,contact:draft.phone},handler:async response=>{const vr=await fetch('/api/verify-payment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(response)});const v=await vr.json();if(!vr.ok||!v.verified)return rej(Error('Payment verification failed'));res({...response,gatewayOrderId:p.id})}});rz.on('payment.failed',()=>rej(Error('Payment failed or cancelled')));rz.open()})}
  $('#checkoutForm').onsubmit=async e=>{e.preventDefault();if(!session?.user)return toast('Please sign in');const items=getCart();if(!items.length)return toast('Your bag is empty');const f=new FormData(e.currentTarget);const draft={name:String(f.get('name')).trim(),email:String(f.get('email')).trim().toLowerCase(),phone:String(f.get('phone')).trim(),address:String(f.get('address')).trim(),payment:String(f.get('payment')),subtotal:cartTotal(),discount:coupon.discount,total:Math.max(0,cartTotal()-coupon.discount)};if(draft.payment==='online'){try{draft.paymentData=await payOnline(draft)}catch(err){return toast(err.message)}}const {data:order,error}=await db.from('orders').insert({user_id:session.user.id,customer_name:draft.name,email:draft.email,phone:draft.phone,address:draft.address,payment_method:draft.payment,payment_status:draft.payment==='online'?'paid':'pending',order_status:'placed',subtotal:draft.subtotal,discount:draft.discount,total:draft.total,coupon_code:coupon.code||null,razorpay_order_id:draft.paymentData?.gatewayOrderId||null,razorpay_payment_id:draft.paymentData?.razorpay_payment_id||null}).select().single();if(error)return toast(error.message);const rows=items.map(i=>({order_id:order.id,product_id:i.id||null,product_name:i.name,price:Number(i.price),quantity:Number(i.qty)}));const {error:ie}=await db.from('order_items').insert(rows);if(ie)return toast('Order saved, but items could not be saved');localStorage.removeItem('elvora-cart');$('.bag-count').textContent='0';coupon={discount:0,code:''};close('checkoutModal');toast(`Order #${order.id.slice(0,8).toUpperCase()} placed`)};
  async function adminGuard(){await loadProfile();if(profile?.role!=='admin'||profile?.active===false){toast('Admin access required');return false}return true}
  async function renderAdmin(){if(!(await adminGuard()))return;const [pr,ord,users,coups]=await Promise.all([db.from('products').select('*').order('created_at',{ascending:false}),db.from('orders').select('*').order('created_at',{ascending:false}).limit(100),db.from('profiles').select('*').order('created_at',{ascending:false}),db.from('coupons').select('*').order('created_at',{ascending:false})]);$('#adminProducts').innerHTML=`<div class="admin-stats"><div><b>${pr.data?.length||0}</b><span>Products</span></div><div><b>${ord.data?.length||0}</b><span>Orders</span></div><div><b>${users.data?.length||0}</b><span>Customers</span></div><div><b>${coups.data?.length||0}</b><span>Coupons</span></div></div><h3>Products</h3>`+(pr.data||[]).map(p=>`<div class="admin-row"><span><strong>${p.name}</strong><small>${p.category} · ₹${Number(p.price).toFixed(0)} · stock ${p.stock} · ${p.active?'Active':'Hidden'}</small></span><div><button data-edit-product="${p.id}">Edit</button><button data-stock-minus="${p.id}">−</button><button data-stock-plus="${p.id}">+</button><button data-db-remove="${p.id}">${p.active?'Hide':'Show'}</button></div></div>`).join('')+`<h3>Orders</h3>`+(ord.data||[]).map(o=>`<div class="admin-row"><span><strong>#${o.id.slice(0,8).toUpperCase()} · ${o.customer_name}</strong><small>₹${Number(o.total).toFixed(2)} · ${o.payment_status}</small></span><select data-order-status="${o.id}">${['placed','confirmed','packed','shipped','delivered','cancelled'].map(s=>`<option ${o.order_status===s?'selected':''}>${s}</option>`).join('')}</select></div>`).join('')+`<h3>Customers</h3>`+(users.data||[]).map(u=>`<div class="admin-row"><span><strong>${u.full_name||'Unnamed'}</strong><small>${u.id} · ${u.phone||'No phone'} · ${u.role}</small></span><button data-user-toggle="${u.id}" ${u.id===session.user.id?'disabled':''}>${u.active?'Disable':'Enable'}</button></div>`).join('')+`<h3>Coupons</h3>`+(coups.data||[]).map(c=>`<div class="admin-row"><span><strong>${c.code}</strong><small>${c.type} ${c.value} · min ₹${c.min_order} · used ${c.used_count}</small></span><button data-coupon-toggle="${c.id}">${c.active?'Disable':'Enable'}</button></div>`).join('');
    $$('[data-db-remove]').forEach(b=>b.onclick=async()=>{const row=(pr.data||[]).find(x=>x.id===b.dataset.dbRemove);const {error}=await db.from('products').update({active:!row.active,updated_at:new Date().toISOString()}).eq('id',row.id);if(error)toast(error.message);else{toast(row.active?'Product hidden':'Product visible');renderAdmin()}});
    $$('[data-edit-product]').forEach(b=>b.onclick=async()=>{const p=(pr.data||[]).find(x=>x.id===b.dataset.editProduct);if(!p)return;const name=prompt('Product name',p.name);if(name===null)return;const price=prompt('Price (INR)',p.price);if(price===null)return;const stock=prompt('Stock',p.stock);if(stock===null)return;const {error}=await db.from('products').update({name:name.trim(),price:Number(price),stock:Number(stock),updated_at:new Date().toISOString()}).eq('id',p.id);if(error)toast(error.message);else{toast('Product updated');await renderAdmin();await syncProducts()}});
    $$('[data-stock-plus]').forEach(b=>b.onclick=()=>changeStock(b.dataset.stockPlus,1));$$('[data-stock-minus]').forEach(b=>b.onclick=()=>changeStock(b.dataset.stockMinus,-1));
    $$('[data-order-status]').forEach(s=>s.onchange=async()=>{const {error}=await db.from('orders').update({order_status:s.value}).eq('id',s.dataset.orderStatus);if(error)toast(error.message);else toast('Order status updated')});
    $$('[data-user-toggle]').forEach(b=>b.onclick=async()=>{const u=(users.data||[]).find(x=>x.id===b.dataset.userToggle);const {error}=await db.from('profiles').update({active:!u.active}).eq('id',u.id);if(error)toast(error.message);else renderAdmin()});
    $$('[data-coupon-toggle]').forEach(b=>b.onclick=async()=>{const c=(coups.data||[]).find(x=>x.id===b.dataset.couponToggle);const {error}=await db.from('coupons').update({active:!c.active}).eq('id',c.id);if(error)toast(error.message);else renderAdmin()});
  }
  async function changeStock(id,delta){const {data}=await db.from('products').select('stock').eq('id',id).single();if(!data)return;const stock=Math.max(0,Number(data.stock)+delta);const {error}=await db.from('products').update({stock,updated_at:new Date().toISOString()}).eq('id',id);if(error)toast(error.message);else renderAdmin()}
  $('#adminTrigger').onclick=async()=>{if(await adminGuard()){await renderAdmin();open('adminModal')}};
  $('#adminForm').onsubmit=async e=>{e.preventDefault();if(!(await adminGuard()))return;const f=new FormData(e.currentTarget);const name=String(f.get('name')).trim();const category=f.get('category');const price=Number(f.get('price'));const stock=Number(f.get('stock')||10);let image=String(f.get('image')).trim();const file=$('#adminFile')?.files?.[0];if(file){const ext=file.name.split('.').pop();const path=`${crypto.randomUUID()}.${ext}`;const up=await db.storage.from('product-images').upload(path,file,{upsert:false});if(up.error)return toast(up.error.message);image=db.storage.from('product-images').getPublicUrl(path).data.publicUrl}if(!image)return toast('Choose an image or enter an image path');const {error}=await db.from('products').insert({name,category,price,image,description:String(f.get('description')||'Premium ELVORA furniture.'),stock,active:true});if(error)return toast(error.message);e.currentTarget.reset();toast('Product added');renderAdmin()};
  $('#adminCouponForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!(await adminGuard()))return;const f=new FormData(e.currentTarget);const {error}=await db.from('coupons').insert({code:String(f.get('code')).trim().toUpperCase(),type:f.get('type'),value:Number(f.get('value')),min_order:Number(f.get('min_order')||0),max_discount:f.get('max_discount')?Number(f.get('max_discount')):null,usage_limit:f.get('usage_limit')?Number(f.get('usage_limit')):null,active:true});if(error)return toast(error.message);e.currentTarget.reset();toast('Coupon created');renderAdmin()});
  loadProfile().then(syncProducts);
  setInterval(syncProducts, 60000);
})();
